<?php

/**
 * Countries.
 */
return [
    [
        'code' => 'ABW',
        'name' => 'Aruba',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 103000,
        'local_name' => 'Aruba',
        'capital' => 129,
        'code2' => 'AW',
    ],
    [
        'code' => 'AFG',
        'name' => 'Afghanistan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 22720000,
        'local_name' => 'Afganistan/Afqanestan',
        'capital' => 1,
        'code2' => 'AF',
    ],
    [
        'code' => 'AGO',
        'name' => 'Angola',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'population' => 12878000,
        'local_name' => 'Angola',
        'capital' => 56,
        'code2' => 'AO',
    ],
    [
        'code' => 'AIA',
        'name' => 'Anguilla',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 8000,
        'local_name' => 'Anguilla',
        'capital' => 62,
        'code2' => 'AI',
    ],
    [
        'code' => 'ALB',
        'name' => 'Albania',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 3401200,
        'local_name' => 'Shqipëria',
        'capital' => 34,
        'code2' => 'AL',
    ],
    [
        'code' => 'AND',
        'name' => 'Andorra',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 78000,
        'local_name' => 'Andorra',
        'capital' => 55,
        'code2' => 'AD',
    ],
    [
        'code' => 'ANT',
        'name' => 'Netherlands Antilles',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 217000,
        'local_name' => 'Nederlandse Antillen',
        'capital' => 33,
        'code2' => 'AN',
    ],
    [
        'code' => 'ARE',
        'name' => 'United Arab Emirates',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 2441000,
        'local_name' => 'Al-Imarat al-´Arabiya al-Muttahida',
        'capital' => 65,
        'code2' => 'AE',
    ],
    [
        'code' => 'ARG',
        'name' => 'Argentina',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 37032000,
        'local_name' => 'Argentina',
        'capital' => 69,
        'code2' => 'AR',
    ],
    [
        'code' => 'ARM',
        'name' => 'Armenia',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 3520000,
        'local_name' => 'Hajastan',
        'capital' => 126,
        'code2' => 'AM',
    ],
    [
        'code' => 'ASM',
        'name' => 'American Samoa',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'population' => 68000,
        'local_name' => 'Amerika Samoa',
        'capital' => 54,
        'code2' => 'AS',
    ],
    [
        'code' => 'ATG',
        'name' => 'Antigua and Barbuda',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 68000,
        'local_name' => 'Antigua and Barbuda',
        'capital' => 63,
        'code2' => 'AG',
    ],
    [
        'code' => 'AUS',
        'name' => 'Australia',
        'continent' => 'Oceania',
        'region' => 'Australia and New Zealand',
        'population' => 18886000,
        'local_name' => 'Australia',
        'capital' => 135,
        'code2' => 'AU',
    ],
    [
        'code' => 'AUT',
        'name' => 'Austria',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'population' => 8091800,
        'local_name' => 'Österreich',
        'capital' => 1523,
        'code2' => 'AT',
    ],
    [
        'code' => 'AZE',
        'name' => 'Azerbaijan',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 7734000,
        'local_name' => 'Azärbaycan',
        'capital' => 144,
        'code2' => 'AZ',
    ],
    [
        'code' => 'BDI',
        'name' => 'Burundi',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 6695000,
        'local_name' => 'Burundi/Uburundi',
        'capital' => 552,
        'code2' => 'BI',
    ],
    [
        'code' => 'BEL',
        'name' => 'Belgium',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'population' => 10239000,
        'local_name' => 'België/Belgique',
        'capital' => 179,
        'code2' => 'BE',
    ],
    [
        'code' => 'BEN',
        'name' => 'Benin',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 6097000,
        'local_name' => 'Bénin',
        'capital' => 187,
        'code2' => 'BJ',
    ],
    [
        'code' => 'BFA',
        'name' => 'Burkina Faso',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 11937000,
        'local_name' => 'Burkina Faso',
        'capital' => 549,
        'code2' => 'BF',
    ],
    [
        'code' => 'BGD',
        'name' => 'Bangladesh',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 129155000,
        'local_name' => 'Bangladesh',
        'capital' => 150,
        'code2' => 'BD',
    ],
    [
        'code' => 'BGR',
        'name' => 'Bulgaria',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'population' => 8190900,
        'local_name' => 'Balgarija',
        'capital' => 539,
        'code2' => 'BG',
    ],
    [
        'code' => 'BHR',
        'name' => 'Bahrain',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 617000,
        'local_name' => 'Al-Bahrayn',
        'capital' => 149,
        'code2' => 'BH',
    ],
    [
        'code' => 'BHS',
        'name' => 'Bahamas',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 307000,
        'local_name' => 'The Bahamas',
        'capital' => 148,
        'code2' => 'BS',
    ],
    [
        'code' => 'BIH',
        'name' => 'Bosnia and Herzegovina',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 3972000,
        'local_name' => 'Bosna i Hercegovina',
        'capital' => 201,
        'code2' => 'BA',
    ],
    [
        'code' => 'BLR',
        'name' => 'Belarus',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'population' => 10236000,
        'local_name' => 'Belarus',
        'capital' => 3520,
        'code2' => 'BY',
    ],
    [
        'code' => 'BLZ',
        'name' => 'Belize',
        'continent' => 'North America',
        'region' => 'Central America',
        'population' => 241000,
        'local_name' => 'Belize',
        'capital' => 185,
        'code2' => 'BZ',
    ],
    [
        'code' => 'BMU',
        'name' => 'Bermuda',
        'continent' => 'North America',
        'region' => 'North America',
        'population' => 65000,
        'local_name' => 'Bermuda',
        'capital' => 191,
        'code2' => 'BM',
    ],
    [
        'code' => 'BOL',
        'name' => 'Bolivia',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 8329000,
        'local_name' => 'Bolivia',
        'capital' => 194,
        'code2' => 'BO',
    ],
    [
        'code' => 'BRA',
        'name' => 'Brazil',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 170115000,
        'local_name' => 'Brasil',
        'capital' => 211,
        'code2' => 'BR',
    ],
    [
        'code' => 'BRB',
        'name' => 'Barbados',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 270000,
        'local_name' => 'Barbados',
        'capital' => 174,
        'code2' => 'BB',
    ],
    [
        'code' => 'BRN',
        'name' => 'Brunei',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'population' => 328000,
        'local_name' => 'Brunei Darussalam',
        'capital' => 538,
        'code2' => 'BN',
    ],
    [
        'code' => 'BTN',
        'name' => 'Bhutan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 2124000,
        'local_name' => 'Druk-Yul',
        'capital' => 192,
        'code2' => 'BT',
    ],
    [
        'code' => 'BWA',
        'name' => 'Botswana',
        'continent' => 'Africa',
        'region' => 'Southern Africa',
        'population' => 1622000,
        'local_name' => 'Botswana',
        'capital' => 204,
        'code2' => 'BW',
    ],
    [
        'code' => 'CAF',
        'name' => 'Central African Republic',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'population' => 3615000,
        'local_name' => 'Centrafrique/Bê-Afrîka',
        'capital' => 1889,
        'code2' => 'CF',
    ],
    [
        'code' => 'CAN',
        'name' => 'Canada',
        'continent' => 'North America',
        'region' => 'North America',
        'population' => 31147000,
        'local_name' => 'Canada',
        'capital' => 1822,
        'code2' => 'CA',
    ],
    [
        'code' => 'CCK',
        'name' => 'Cocos (Keeling) Islands',
        'continent' => 'Oceania',
        'region' => 'Australia and New Zealand',
        'population' => 600,
        'local_name' => 'Cocos (Keeling) Islands',
        'capital' => 2317,
        'code2' => 'CC',
    ],
    [
        'code' => 'CHE',
        'name' => 'Switzerland',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'population' => 7160400,
        'local_name' => 'Schweiz/Suisse/Svizzera/Svizra',
        'capital' => 3248,
        'code2' => 'CH',
    ],
    [
        'code' => 'CHL',
        'name' => 'Chile',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 15211000,
        'local_name' => 'Chile',
        'capital' => 554,
        'code2' => 'CL',
    ],
    [
        'code' => 'CHN',
        'name' => 'China',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'population' => 1277558000,
        'local_name' => 'Zhongquo',
        'capital' => 1891,
        'code2' => 'CN',
    ],
    [
        'code' => 'CIV',
        'name' => 'Côte d’Ivoire',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 14786000,
        'local_name' => 'Côte d’Ivoire',
        'capital' => 2814,
        'code2' => 'CI',
    ],
    [
        'code' => 'CMR',
        'name' => 'Cameroon',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'population' => 15085000,
        'local_name' => 'Cameroun/Cameroon',
        'capital' => 1804,
        'code2' => 'CM',
    ],
    [
        'code' => 'COD',
        'name' => 'Congo, The Democratic Republic of the',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'population' => 51654000,
        'local_name' => 'République Démocratique du Congo',
        'capital' => 2298,
        'code2' => 'CD',
    ],
    [
        'code' => 'COG',
        'name' => 'Congo',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'population' => 2943000,
        'local_name' => 'Congo',
        'capital' => 2296,
        'code2' => 'CG',
    ],
    [
        'code' => 'COK',
        'name' => 'Cook Islands',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'population' => 20000,
        'local_name' => 'The Cook Islands',
        'capital' => 583,
        'code2' => 'CK',
    ],
    [
        'code' => 'COL',
        'name' => 'Colombia',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 42321000,
        'local_name' => 'Colombia',
        'capital' => 2257,
        'code2' => 'CO',
    ],
    [
        'code' => 'COM',
        'name' => 'Comoros',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 578000,
        'local_name' => 'Komori/Comores',
        'capital' => 2295,
        'code2' => 'KM',
    ],
    [
        'code' => 'CPV',
        'name' => 'Cape Verde',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 428000,
        'local_name' => 'Cabo Verde',
        'capital' => 1859,
        'code2' => 'CV',
    ],
    [
        'code' => 'CRI',
        'name' => 'Costa Rica',
        'continent' => 'North America',
        'region' => 'Central America',
        'population' => 4023000,
        'local_name' => 'Costa Rica',
        'capital' => 584,
        'code2' => 'CR',
    ],
    [
        'code' => 'CUB',
        'name' => 'Cuba',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 11201000,
        'local_name' => 'Cuba',
        'capital' => 2413,
        'code2' => 'CU',
    ],
    [
        'code' => 'CXR',
        'name' => 'Christmas Island',
        'continent' => 'Oceania',
        'region' => 'Australia and New Zealand',
        'population' => 2500,
        'local_name' => 'Christmas Island',
        'capital' => 1791,
        'code2' => 'CX',
    ],
    [
        'code' => 'CYM',
        'name' => 'Cayman Islands',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 38000,
        'local_name' => 'Cayman Islands',
        'capital' => 553,
        'code2' => 'KY',
    ],
    [
        'code' => 'CYP',
        'name' => 'Cyprus',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 754700,
        'local_name' => 'Kýpros/Kibris',
        'capital' => 2430,
        'code2' => 'CY',
    ],
    [
        'code' => 'CZE',
        'name' => 'Czech Republic',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'population' => 10278100,
        'local_name' => '¸esko',
        'capital' => 3339,
        'code2' => 'CZ',
    ],
    [
        'code' => 'DEU',
        'name' => 'Germany',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'population' => 82164700,
        'local_name' => 'Deutschland',
        'capital' => 3068,
        'code2' => 'DE',
    ],
    [
        'code' => 'DJI',
        'name' => 'Djibouti',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 638000,
        'local_name' => 'Djibouti/Jibuti',
        'capital' => 585,
        'code2' => 'DJ',
    ],
    [
        'code' => 'DMA',
        'name' => 'Dominica',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 71000,
        'local_name' => 'Dominica',
        'capital' => 586,
        'code2' => 'DM',
    ],
    [
        'code' => 'DNK',
        'name' => 'Denmark',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'population' => 5330000,
        'local_name' => 'Danmark',
        'capital' => 3315,
        'code2' => 'DK',
    ],
    [
        'code' => 'DOM',
        'name' => 'Dominican Republic',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 8495000,
        'local_name' => 'República Dominicana',
        'capital' => 587,
        'code2' => 'DO',
    ],
    [
        'code' => 'DZA',
        'name' => 'Algeria',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'population' => 31471000,
        'local_name' => 'Al-Jaza’ir/Algérie',
        'capital' => 35,
        'code2' => 'DZ',
    ],
    [
        'code' => 'ECU',
        'name' => 'Ecuador',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 12646000,
        'local_name' => 'Ecuador',
        'capital' => 594,
        'code2' => 'EC',
    ],
    [
        'code' => 'EGY',
        'name' => 'Egypt',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'population' => 68470000,
        'local_name' => 'Misr',
        'capital' => 608,
        'code2' => 'EG',
    ],
    [
        'code' => 'ERI',
        'name' => 'Eritrea',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 3850000,
        'local_name' => 'Ertra',
        'capital' => 652,
        'code2' => 'ER',
    ],
    [
        'code' => 'ESH',
        'name' => 'Western Sahara',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'population' => 293000,
        'local_name' => 'As-Sahrawiya',
        'capital' => 2453,
        'code2' => 'EH',
    ],
    [
        'code' => 'ESP',
        'name' => 'Spain',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 39441700,
        'local_name' => 'España',
        'capital' => 653,
        'code2' => 'ES',
    ],
    [
        'code' => 'EST',
        'name' => 'Estonia',
        'continent' => 'Europe',
        'region' => 'Baltic Countries',
        'population' => 1439200,
        'local_name' => 'Eesti',
        'capital' => 3791,
        'code2' => 'EE',
    ],
    [
        'code' => 'ETH',
        'name' => 'Ethiopia',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 62565000,
        'local_name' => 'YeItyop´iya',
        'capital' => 756,
        'code2' => 'ET',
    ],
    [
        'code' => 'FIN',
        'name' => 'Finland',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'population' => 5171300,
        'local_name' => 'Suomi',
        'capital' => 3236,
        'code2' => 'FI',
    ],
    [
        'code' => 'FJI',
        'name' => 'Fiji Islands',
        'continent' => 'Oceania',
        'region' => 'Melanesia',
        'population' => 817000,
        'local_name' => 'Fiji Islands',
        'capital' => 764,
        'code2' => 'FJ',
    ],
    [
        'code' => 'FLK',
        'name' => 'Falkland Islands',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 2000,
        'local_name' => 'Falkland Islands',
        'capital' => 763,
        'code2' => 'FK',
    ],
    [
        'code' => 'FRA',
        'name' => 'France',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'population' => 59225700,
        'local_name' => 'France',
        'capital' => 2974,
        'code2' => 'FR',
    ],
    [
        'code' => 'FRO',
        'name' => 'Faroe Islands',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'population' => 43000,
        'local_name' => 'Føroyar',
        'capital' => 901,
        'code2' => 'FO',
    ],
    [
        'code' => 'FSM',
        'name' => 'Micronesia, Federated States of',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'population' => 119000,
        'local_name' => 'Micronesia',
        'capital' => 2689,
        'code2' => 'FM',
    ],
    [
        'code' => 'GAB',
        'name' => 'Gabon',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'population' => 1226000,
        'local_name' => 'Le Gabon',
        'capital' => 902,
        'code2' => 'GA',
    ],
    [
        'code' => 'GBR',
        'name' => 'United Kingdom',
        'continent' => 'Europe',
        'region' => 'British Islands',
        'population' => 59623400,
        'local_name' => 'United Kingdom',
        'capital' => 456,
        'code2' => 'GB',
    ],
    [
        'code' => 'GEO',
        'name' => 'Georgia',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 4968000,
        'local_name' => 'Sakartvelo',
        'capital' => 905,
        'code2' => 'GE',
    ],
    [
        'code' => 'GHA',
        'name' => 'Ghana',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 20212000,
        'local_name' => 'Ghana',
        'capital' => 910,
        'code2' => 'GH',
    ],
    [
        'code' => 'GIB',
        'name' => 'Gibraltar',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 25000,
        'local_name' => 'Gibraltar',
        'capital' => 915,
        'code2' => 'GI',
    ],
    [
        'code' => 'GIN',
        'name' => 'Guinea',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 7430000,
        'local_name' => 'Guinée',
        'capital' => 926,
        'code2' => 'GN',
    ],
    [
        'code' => 'GLP',
        'name' => 'Guadeloupe',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 456000,
        'local_name' => 'Guadeloupe',
        'capital' => 919,
        'code2' => 'GP',
    ],
    [
        'code' => 'GMB',
        'name' => 'Gambia',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 1305000,
        'local_name' => 'The Gambia',
        'capital' => 904,
        'code2' => 'GM',
    ],
    [
        'code' => 'GNB',
        'name' => 'Guinea-Bissau',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 1213000,
        'local_name' => 'Guiné-Bissau',
        'capital' => 927,
        'code2' => 'GW',
    ],
    [
        'code' => 'GNQ',
        'name' => 'Equatorial Guinea',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'population' => 453000,
        'local_name' => 'Guinea Ecuatorial',
        'capital' => 2972,
        'code2' => 'GQ',
    ],
    [
        'code' => 'GRC',
        'name' => 'Greece',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 10545700,
        'local_name' => 'Elláda',
        'capital' => 2401,
        'code2' => 'GR',
    ],
    [
        'code' => 'GRD',
        'name' => 'Grenada',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 94000,
        'local_name' => 'Grenada',
        'capital' => 916,
        'code2' => 'GD',
    ],
    [
        'code' => 'GRL',
        'name' => 'Greenland',
        'continent' => 'North America',
        'region' => 'North America',
        'population' => 56000,
        'local_name' => 'Kalaallit Nunaat/Grønland',
        'capital' => 917,
        'code2' => 'GL',
    ],
    [
        'code' => 'GTM',
        'name' => 'Guatemala',
        'continent' => 'North America',
        'region' => 'Central America',
        'population' => 11385000,
        'local_name' => 'Guatemala',
        'capital' => 922,
        'code2' => 'GT',
    ],
    [
        'code' => 'GUF',
        'name' => 'French Guiana',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 181000,
        'local_name' => 'Guyane française',
        'capital' => 3014,
        'code2' => 'GF',
    ],
    [
        'code' => 'GUM',
        'name' => 'Guam',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'population' => 168000,
        'local_name' => 'Guam',
        'capital' => 921,
        'code2' => 'GU',
    ],
    [
        'code' => 'GUY',
        'name' => 'Guyana',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 861000,
        'local_name' => 'Guyana',
        'capital' => 928,
        'code2' => 'GY',
    ],
    [
        'code' => 'HKG',
        'name' => 'Hong Kong',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'population' => 6782000,
        'local_name' => 'Xianggang/Hong Kong',
        'capital' => 937,
        'code2' => 'HK',
    ],
    [
        'code' => 'HND',
        'name' => 'Honduras',
        'continent' => 'North America',
        'region' => 'Central America',
        'population' => 6485000,
        'local_name' => 'Honduras',
        'capital' => 933,
        'code2' => 'HN',
    ],
    [
        'code' => 'HRV',
        'name' => 'Croatia',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 4473000,
        'local_name' => 'Hrvatska',
        'capital' => 2409,
        'code2' => 'HR',
    ],
    [
        'code' => 'HTI',
        'name' => 'Haiti',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 8222000,
        'local_name' => 'Haïti/Dayti',
        'capital' => 929,
        'code2' => 'HT',
    ],
    [
        'code' => 'HUN',
        'name' => 'Hungary',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'population' => 10043200,
        'local_name' => 'Magyarország',
        'capital' => 3483,
        'code2' => 'HU',
    ],
    [
        'code' => 'IDN',
        'name' => 'Indonesia',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'population' => 212107000,
        'local_name' => 'Indonesia',
        'capital' => 939,
        'code2' => 'ID',
    ],
    [
        'code' => 'IND',
        'name' => 'India',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 1013662000,
        'local_name' => 'Bharat/India',
        'capital' => 1109,
        'code2' => 'IN',
    ],
    [
        'code' => 'IRL',
        'name' => 'Ireland',
        'continent' => 'Europe',
        'region' => 'British Islands',
        'population' => 3775100,
        'local_name' => 'Ireland/Éire',
        'capital' => 1447,
        'code2' => 'IE',
    ],
    [
        'code' => 'IRN',
        'name' => 'Iran',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 67702000,
        'local_name' => 'Iran',
        'capital' => 1380,
        'code2' => 'IR',
    ],
    [
        'code' => 'IRQ',
        'name' => 'Iraq',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 23115000,
        'local_name' => 'Al-´Iraq',
        'capital' => 1365,
        'code2' => 'IQ',
    ],
    [
        'code' => 'ISL',
        'name' => 'Iceland',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'population' => 279000,
        'local_name' => 'Ísland',
        'capital' => 1449,
        'code2' => 'IS',
    ],
    [
        'code' => 'ISR',
        'name' => 'Israel',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 6217000,
        'local_name' => 'Yisra’el/Isra’il',
        'capital' => 1450,
        'code2' => 'IL',
    ],
    [
        'code' => 'ITA',
        'name' => 'Italy',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 57680000,
        'local_name' => 'Italia',
        'capital' => 1464,
        'code2' => 'IT',
    ],
    [
        'code' => 'JAM',
        'name' => 'Jamaica',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 2583000,
        'local_name' => 'Jamaica',
        'capital' => 1530,
        'code2' => 'JM',
    ],
    [
        'code' => 'JOR',
        'name' => 'Jordan',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 5083000,
        'local_name' => 'Al-Urdunn',
        'capital' => 1786,
        'code2' => 'JO',
    ],
    [
        'code' => 'JPN',
        'name' => 'Japan',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'population' => 126714000,
        'local_name' => 'Nihon/Nippon',
        'capital' => 1532,
        'code2' => 'JP',
    ],
    [
        'code' => 'KAZ',
        'name' => 'Kazakstan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 16223000,
        'local_name' => 'Qazaqstan',
        'capital' => 1864,
        'code2' => 'KZ',
    ],
    [
        'code' => 'KEN',
        'name' => 'Kenya',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 30080000,
        'local_name' => 'Kenya',
        'capital' => 1881,
        'code2' => 'KE',
    ],
    [
        'code' => 'KGZ',
        'name' => 'Kyrgyzstan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 4699000,
        'local_name' => 'Kyrgyzstan',
        'capital' => 2253,
        'code2' => 'KG',
    ],
    [
        'code' => 'KHM',
        'name' => 'Cambodia',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'population' => 11168000,
        'local_name' => 'Kâmpuchéa',
        'capital' => 1800,
        'code2' => 'KH',
    ],
    [
        'code' => 'KIR',
        'name' => 'Kiribati',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'population' => 83000,
        'local_name' => 'Kiribati',
        'capital' => 2256,
        'code2' => 'KI',
    ],
    [
        'code' => 'KNA',
        'name' => 'Saint Kitts and Nevis',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 38000,
        'local_name' => 'Saint Kitts and Nevis',
        'capital' => 3064,
        'code2' => 'KN',
    ],
    [
        'code' => 'KOR',
        'name' => 'South Korea',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'population' => 46844000,
        'local_name' => 'Taehan Min’guk (Namhan)',
        'capital' => 2331,
        'code2' => 'KR',
    ],
    [
        'code' => 'KWT',
        'name' => 'Kuwait',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 1972000,
        'local_name' => 'Al-Kuwayt',
        'capital' => 2429,
        'code2' => 'KW',
    ],
    [
        'code' => 'LAO',
        'name' => 'Laos',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'population' => 5433000,
        'local_name' => 'Lao',
        'capital' => 2432,
        'code2' => 'LA',
    ],
    [
        'code' => 'LBN',
        'name' => 'Lebanon',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 3282000,
        'local_name' => 'Lubnan',
        'capital' => 2438,
        'code2' => 'LB',
    ],
    [
        'code' => 'LBR',
        'name' => 'Liberia',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 3154000,
        'local_name' => 'Liberia',
        'capital' => 2440,
        'code2' => 'LR',
    ],
    [
        'code' => 'LBY',
        'name' => 'Libyan Arab Jamahiriya',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'population' => 5605000,
        'local_name' => 'Libiya',
        'capital' => 2441,
        'code2' => 'LY',
    ],
    [
        'code' => 'LCA',
        'name' => 'Saint Lucia',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 154000,
        'local_name' => 'Saint Lucia',
        'capital' => 3065,
        'code2' => 'LC',
    ],
    [
        'code' => 'LIE',
        'name' => 'Liechtenstein',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'population' => 32300,
        'local_name' => 'Liechtenstein',
        'capital' => 2446,
        'code2' => 'LI',
    ],
    [
        'code' => 'LKA',
        'name' => 'Sri Lanka',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 18827000,
        'local_name' => 'Sri Lanka/Ilankai',
        'capital' => 3217,
        'code2' => 'LK',
    ],
    [
        'code' => 'LSO',
        'name' => 'Lesotho',
        'continent' => 'Africa',
        'region' => 'Southern Africa',
        'population' => 2153000,
        'local_name' => 'Lesotho',
        'capital' => 2437,
        'code2' => 'LS',
    ],
    [
        'code' => 'LTU',
        'name' => 'Lithuania',
        'continent' => 'Europe',
        'region' => 'Baltic Countries',
        'population' => 3698500,
        'local_name' => 'Lietuva',
        'capital' => 2447,
        'code2' => 'LT',
    ],
    [
        'code' => 'LUX',
        'name' => 'Luxembourg',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'population' => 435700,
        'local_name' => 'Luxembourg/Lëtzebuerg',
        'capital' => 2452,
        'code2' => 'LU',
    ],
    [
        'code' => 'LVA',
        'name' => 'Latvia',
        'continent' => 'Europe',
        'region' => 'Baltic Countries',
        'population' => 2424200,
        'local_name' => 'Latvija',
        'capital' => 2434,
        'code2' => 'LV',
    ],
    [
        'code' => 'MAC',
        'name' => 'Macao',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'population' => 473000,
        'local_name' => 'Macau/Aomen',
        'capital' => 2454,
        'code2' => 'MO',
    ],
    [
        'code' => 'MAR',
        'name' => 'Morocco',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'population' => 28351000,
        'local_name' => 'Al-Maghrib',
        'capital' => 2486,
        'code2' => 'MA',
    ],
    [
        'code' => 'MCO',
        'name' => 'Monaco',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'population' => 34000,
        'local_name' => 'Monaco',
        'capital' => 2695,
        'code2' => 'MC',
    ],
    [
        'code' => 'MDA',
        'name' => 'Moldova',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'population' => 4380000,
        'local_name' => 'Moldova',
        'capital' => 2690,
        'code2' => 'MD',
    ],
    [
        'code' => 'MDG',
        'name' => 'Madagascar',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 15942000,
        'local_name' => 'Madagasikara/Madagascar',
        'capital' => 2455,
        'code2' => 'MG',
    ],
    [
        'code' => 'MDV',
        'name' => 'Maldives',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 286000,
        'local_name' => 'Dhivehi Raajje/Maldives',
        'capital' => 2463,
        'code2' => 'MV',
    ],
    [
        'code' => 'MEX',
        'name' => 'Mexico',
        'continent' => 'North America',
        'region' => 'Central America',
        'population' => 98881000,
        'local_name' => 'México',
        'capital' => 2515,
        'code2' => 'MX',
    ],
    [
        'code' => 'MHL',
        'name' => 'Marshall Islands',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'population' => 64000,
        'local_name' => 'Marshall Islands/Majol',
        'capital' => 2507,
        'code2' => 'MH',
    ],
    [
        'code' => 'MKD',
        'name' => 'Macedonia',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 2024000,
        'local_name' => 'Makedonija',
        'capital' => 2460,
        'code2' => 'MK',
    ],
    [
        'code' => 'MLI',
        'name' => 'Mali',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 11234000,
        'local_name' => 'Mali',
        'capital' => 2482,
        'code2' => 'ML',
    ],
    [
        'code' => 'MLT',
        'name' => 'Malta',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 380200,
        'local_name' => 'Malta',
        'capital' => 2484,
        'code2' => 'MT',
    ],
    [
        'code' => 'MMR',
        'name' => 'Myanmar',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'population' => 45611000,
        'local_name' => 'Myanma Pye',
        'capital' => 2710,
        'code2' => 'MM',
    ],
    [
        'code' => 'MNG',
        'name' => 'Mongolia',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'population' => 2662000,
        'local_name' => 'Mongol Uls',
        'capital' => 2696,
        'code2' => 'MN',
    ],
    [
        'code' => 'MNP',
        'name' => 'Northern Mariana Islands',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'population' => 78000,
        'local_name' => 'Northern Mariana Islands',
        'capital' => 2913,
        'code2' => 'MP',
    ],
    [
        'code' => 'MOZ',
        'name' => 'Mozambique',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 19680000,
        'local_name' => 'Moçambique',
        'capital' => 2698,
        'code2' => 'MZ',
    ],
    [
        'code' => 'MRT',
        'name' => 'Mauritania',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 2670000,
        'local_name' => 'Muritaniya/Mauritanie',
        'capital' => 2509,
        'code2' => 'MR',
    ],
    [
        'code' => 'MSR',
        'name' => 'Montserrat',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 11000,
        'local_name' => 'Montserrat',
        'capital' => 2697,
        'code2' => 'MS',
    ],
    [
        'code' => 'MTQ',
        'name' => 'Martinique',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 395000,
        'local_name' => 'Martinique',
        'capital' => 2508,
        'code2' => 'MQ',
    ],
    [
        'code' => 'MUS',
        'name' => 'Mauritius',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 1158000,
        'local_name' => 'Mauritius',
        'capital' => 2511,
        'code2' => 'MU',
    ],
    [
        'code' => 'MWI',
        'name' => 'Malawi',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 10925000,
        'local_name' => 'Malawi',
        'capital' => 2462,
        'code2' => 'MW',
    ],
    [
        'code' => 'MYS',
        'name' => 'Malaysia',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'population' => 22244000,
        'local_name' => 'Malaysia',
        'capital' => 2464,
        'code2' => 'MY',
    ],
    [
        'code' => 'MYT',
        'name' => 'Mayotte',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 149000,
        'local_name' => 'Mayotte',
        'capital' => 2514,
        'code2' => 'YT',
    ],
    [
        'code' => 'NAM',
        'name' => 'Namibia',
        'continent' => 'Africa',
        'region' => 'Southern Africa',
        'population' => 1726000,
        'local_name' => 'Namibia',
        'capital' => 2726,
        'code2' => 'NA',
    ],
    [
        'code' => 'NCL',
        'name' => 'New Caledonia',
        'continent' => 'Oceania',
        'region' => 'Melanesia',
        'population' => 214000,
        'local_name' => 'Nouvelle-Calédonie',
        'capital' => 3493,
        'code2' => 'NC',
    ],
    [
        'code' => 'NER',
        'name' => 'Niger',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 10730000,
        'local_name' => 'Niger',
        'capital' => 2738,
        'code2' => 'NE',
    ],
    [
        'code' => 'NFK',
        'name' => 'Norfolk Island',
        'continent' => 'Oceania',
        'region' => 'Australia and New Zealand',
        'population' => 2000,
        'local_name' => 'Norfolk Island',
        'capital' => 2806,
        'code2' => 'NF',
    ],
    [
        'code' => 'NGA',
        'name' => 'Nigeria',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 111506000,
        'local_name' => 'Nigeria',
        'capital' => 2754,
        'code2' => 'NG',
    ],
    [
        'code' => 'NIC',
        'name' => 'Nicaragua',
        'continent' => 'North America',
        'region' => 'Central America',
        'population' => 5074000,
        'local_name' => 'Nicaragua',
        'capital' => 2734,
        'code2' => 'NI',
    ],
    [
        'code' => 'NIU',
        'name' => 'Niue',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'population' => 2000,
        'local_name' => 'Niue',
        'capital' => 2805,
        'code2' => 'NU',
    ],
    [
        'code' => 'NLD',
        'name' => 'Netherlands',
        'continent' => 'Europe',
        'region' => 'Western Europe',
        'population' => 15864000,
        'local_name' => 'Nederland',
        'capital' => 5,
        'code2' => 'NL',
    ],
    [
        'code' => 'NOR',
        'name' => 'Norway',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'population' => 4478500,
        'local_name' => 'Norge',
        'capital' => 2807,
        'code2' => 'NO',
    ],
    [
        'code' => 'NPL',
        'name' => 'Nepal',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 23930000,
        'local_name' => 'Nepal',
        'capital' => 2729,
        'code2' => 'NP',
    ],
    [
        'code' => 'NRU',
        'name' => 'Nauru',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'population' => 12000,
        'local_name' => 'Naoero/Nauru',
        'capital' => 2728,
        'code2' => 'NR',
    ],
    [
        'code' => 'NZL',
        'name' => 'New Zealand',
        'continent' => 'Oceania',
        'region' => 'Australia and New Zealand',
        'population' => 3862000,
        'local_name' => 'New Zealand/Aotearoa',
        'capital' => 3499,
        'code2' => 'NZ',
    ],
    [
        'code' => 'OMN',
        'name' => 'Oman',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 2542000,
        'local_name' => '´Uman',
        'capital' => 2821,
        'code2' => 'OM',
    ],
    [
        'code' => 'PAK',
        'name' => 'Pakistan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 156483000,
        'local_name' => 'Pakistan',
        'capital' => 2831,
        'code2' => 'PK',
    ],
    [
        'code' => 'PAN',
        'name' => 'Panama',
        'continent' => 'North America',
        'region' => 'Central America',
        'population' => 2856000,
        'local_name' => 'Panamá',
        'capital' => 2882,
        'code2' => 'PA',
    ],
    [
        'code' => 'PCN',
        'name' => 'Pitcairn',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'population' => 50,
        'local_name' => 'Pitcairn',
        'capital' => 2912,
        'code2' => 'PN',
    ],
    [
        'code' => 'PER',
        'name' => 'Peru',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 25662000,
        'local_name' => 'Perú/Piruw',
        'capital' => 2890,
        'code2' => 'PE',
    ],
    [
        'code' => 'PHL',
        'name' => 'Philippines',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'population' => 75967000,
        'local_name' => 'Pilipinas',
        'capital' => 766,
        'code2' => 'PH',
    ],
    [
        'code' => 'PLW',
        'name' => 'Palau',
        'continent' => 'Oceania',
        'region' => 'Micronesia',
        'population' => 19000,
        'local_name' => 'Belau/Palau',
        'capital' => 2881,
        'code2' => 'PW',
    ],
    [
        'code' => 'PNG',
        'name' => 'Papua New Guinea',
        'continent' => 'Oceania',
        'region' => 'Melanesia',
        'population' => 4807000,
        'local_name' => 'Papua New Guinea/Papua Niugini',
        'capital' => 2884,
        'code2' => 'PG',
    ],
    [
        'code' => 'POL',
        'name' => 'Poland',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'population' => 38653600,
        'local_name' => 'Polska',
        'capital' => 2928,
        'code2' => 'PL',
    ],
    [
        'code' => 'PRI',
        'name' => 'Puerto Rico',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 3869000,
        'local_name' => 'Puerto Rico',
        'capital' => 2919,
        'code2' => 'PR',
    ],
    [
        'code' => 'PRK',
        'name' => 'North Korea',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'population' => 24039000,
        'local_name' => 'Choson Minjujuui In´min Konghwaguk (Bukhan)',
        'capital' => 2318,
        'code2' => 'KP',
    ],
    [
        'code' => 'PRT',
        'name' => 'Portugal',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 9997600,
        'local_name' => 'Portugal',
        'capital' => 2914,
        'code2' => 'PT',
    ],
    [
        'code' => 'PRY',
        'name' => 'Paraguay',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 5496000,
        'local_name' => 'Paraguay',
        'capital' => 2885,
        'code2' => 'PY',
    ],
    [
        'code' => 'PSE',
        'name' => 'Palestine',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 3101000,
        'local_name' => 'Filastin',
        'capital' => 4074,
        'code2' => 'PS',
    ],
    [
        'code' => 'PYF',
        'name' => 'French Polynesia',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'population' => 235000,
        'local_name' => 'Polynésie française',
        'capital' => 3016,
        'code2' => 'PF',
    ],
    [
        'code' => 'QAT',
        'name' => 'Qatar',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 599000,
        'local_name' => 'Qatar',
        'capital' => 2973,
        'code2' => 'QA',
    ],
    [
        'code' => 'REU',
        'name' => 'Réunion',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 699000,
        'local_name' => 'Réunion',
        'capital' => 3017,
        'code2' => 'RE',
    ],
    [
        'code' => 'ROM',
        'name' => 'Romania',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'population' => 22455500,
        'local_name' => 'România',
        'capital' => 3018,
        'code2' => 'RO',
    ],
    [
        'code' => 'RUS',
        'name' => 'Russian Federation',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'population' => 146934000,
        'local_name' => 'Rossija',
        'capital' => 3580,
        'code2' => 'RU',
    ],
    [
        'code' => 'RWA',
        'name' => 'Rwanda',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 7733000,
        'local_name' => 'Rwanda/Urwanda',
        'capital' => 3047,
        'code2' => 'RW',
    ],
    [
        'code' => 'SAU',
        'name' => 'Saudi Arabia',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 21607000,
        'local_name' => 'Al-´Arabiya as-Sa´udiya',
        'capital' => 3173,
        'code2' => 'SA',
    ],
    [
        'code' => 'SDN',
        'name' => 'Sudan',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'population' => 29490000,
        'local_name' => 'As-Sudan',
        'capital' => 3225,
        'code2' => 'SD',
    ],
    [
        'code' => 'SEN',
        'name' => 'Senegal',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 9481000,
        'local_name' => 'Sénégal/Sounougal',
        'capital' => 3198,
        'code2' => 'SN',
    ],
    [
        'code' => 'SGP',
        'name' => 'Singapore',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'population' => 3567000,
        'local_name' => 'Singapore/Singapura/Xinjiapo/Singapur',
        'capital' => 3208,
        'code2' => 'SG',
    ],
    [
        'code' => 'SHN',
        'name' => 'Saint Helena',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 6000,
        'local_name' => 'Saint Helena',
        'capital' => 3063,
        'code2' => 'SH',
    ],
    [
        'code' => 'SJM',
        'name' => 'Svalbard and Jan Mayen',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'population' => 3200,
        'local_name' => 'Svalbard og Jan Mayen',
        'capital' => 938,
        'code2' => 'SJ',
    ],
    [
        'code' => 'SLB',
        'name' => 'Solomon Islands',
        'continent' => 'Oceania',
        'region' => 'Melanesia',
        'population' => 444000,
        'local_name' => 'Solomon Islands',
        'capital' => 3161,
        'code2' => 'SB',
    ],
    [
        'code' => 'SLE',
        'name' => 'Sierra Leone',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 4854000,
        'local_name' => 'Sierra Leone',
        'capital' => 3207,
        'code2' => 'SL',
    ],
    [
        'code' => 'SLV',
        'name' => 'El Salvador',
        'continent' => 'North America',
        'region' => 'Central America',
        'population' => 6276000,
        'local_name' => 'El Salvador',
        'capital' => 645,
        'code2' => 'SV',
    ],
    [
        'code' => 'SMR',
        'name' => 'San Marino',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 27000,
        'local_name' => 'San Marino',
        'capital' => 3171,
        'code2' => 'SM',
    ],
    [
        'code' => 'SOM',
        'name' => 'Somalia',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 10097000,
        'local_name' => 'Soomaaliya',
        'capital' => 3214,
        'code2' => 'SO',
    ],
    [
        'code' => 'SPM',
        'name' => 'Saint Pierre and Miquelon',
        'continent' => 'North America',
        'region' => 'North America',
        'population' => 7000,
        'local_name' => 'Saint-Pierre-et-Miquelon',
        'capital' => 3067,
        'code2' => 'PM',
    ],
    [
        'code' => 'STP',
        'name' => 'Sao Tome and Principe',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'population' => 147000,
        'local_name' => 'São Tomé e Príncipe',
        'capital' => 3172,
        'code2' => 'ST',
    ],
    [
        'code' => 'SUR',
        'name' => 'Suriname',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 417000,
        'local_name' => 'Suriname',
        'capital' => 3243,
        'code2' => 'SR',
    ],
    [
        'code' => 'SVK',
        'name' => 'Slovakia',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'population' => 5398700,
        'local_name' => 'Slovensko',
        'capital' => 3209,
        'code2' => 'SK',
    ],
    [
        'code' => 'SVN',
        'name' => 'Slovenia',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 1987800,
        'local_name' => 'Slovenija',
        'capital' => 3212,
        'code2' => 'SI',
    ],
    [
        'code' => 'SWE',
        'name' => 'Sweden',
        'continent' => 'Europe',
        'region' => 'Nordic Countries',
        'population' => 8861400,
        'local_name' => 'Sverige',
        'capital' => 3048,
        'code2' => 'SE',
    ],
    [
        'code' => 'SWZ',
        'name' => 'Swaziland',
        'continent' => 'Africa',
        'region' => 'Southern Africa',
        'population' => 1008000,
        'local_name' => 'kaNgwane',
        'capital' => 3244,
        'code2' => 'SZ',
    ],
    [
        'code' => 'SYC',
        'name' => 'Seychelles',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 77000,
        'local_name' => 'Sesel/Seychelles',
        'capital' => 3206,
        'code2' => 'SC',
    ],
    [
        'code' => 'SYR',
        'name' => 'Syria',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 16125000,
        'local_name' => 'Suriya',
        'capital' => 3250,
        'code2' => 'SY',
    ],
    [
        'code' => 'TCA',
        'name' => 'Turks and Caicos Islands',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 17000,
        'local_name' => 'The Turks and Caicos Islands',
        'capital' => 3423,
        'code2' => 'TC',
    ],
    [
        'code' => 'TCD',
        'name' => 'Chad',
        'continent' => 'Africa',
        'region' => 'Central Africa',
        'population' => 7651000,
        'local_name' => 'Tchad/Tshad',
        'capital' => 3337,
        'code2' => 'TD',
    ],
    [
        'code' => 'TGO',
        'name' => 'Togo',
        'continent' => 'Africa',
        'region' => 'Western Africa',
        'population' => 4629000,
        'local_name' => 'Togo',
        'capital' => 3332,
        'code2' => 'TG',
    ],
    [
        'code' => 'THA',
        'name' => 'Thailand',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'population' => 61399000,
        'local_name' => 'Prathet Thai',
        'capital' => 3320,
        'code2' => 'TH',
    ],
    [
        'code' => 'TJK',
        'name' => 'Tajikistan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 6188000,
        'local_name' => 'Toçikiston',
        'capital' => 3261,
        'code2' => 'TJ',
    ],
    [
        'code' => 'TKL',
        'name' => 'Tokelau',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'population' => 2000,
        'local_name' => 'Tokelau',
        'capital' => 3333,
        'code2' => 'TK',
    ],
    [
        'code' => 'TKM',
        'name' => 'Turkmenistan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 4459000,
        'local_name' => 'Türkmenostan',
        'capital' => 3419,
        'code2' => 'TM',
    ],
    [
        'code' => 'TMP',
        'name' => 'East Timor',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'population' => 885000,
        'local_name' => 'Timor Timur',
        'capital' => 1522,
        'code2' => 'TP',
    ],
    [
        'code' => 'TON',
        'name' => 'Tonga',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'population' => 99000,
        'local_name' => 'Tonga',
        'capital' => 3334,
        'code2' => 'TO',
    ],
    [
        'code' => 'TTO',
        'name' => 'Trinidad and Tobago',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 1295000,
        'local_name' => 'Trinidad and Tobago',
        'capital' => 3336,
        'code2' => 'TT',
    ],
    [
        'code' => 'TUN',
        'name' => 'Tunisia',
        'continent' => 'Africa',
        'region' => 'Northern Africa',
        'population' => 9586000,
        'local_name' => 'Tunis/Tunisie',
        'capital' => 3349,
        'code2' => 'TN',
    ],
    [
        'code' => 'TUR',
        'name' => 'Turkey',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 66591000,
        'local_name' => 'Türkiye',
        'capital' => 3358,
        'code2' => 'TR',
    ],
    [
        'code' => 'TUV',
        'name' => 'Tuvalu',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'population' => 12000,
        'local_name' => 'Tuvalu',
        'capital' => 3424,
        'code2' => 'TV',
    ],
    [
        'code' => 'TWN',
        'name' => 'Taiwan',
        'continent' => 'Asia',
        'region' => 'Eastern Asia',
        'population' => 22256000,
        'local_name' => 'T’ai-wan',
        'capital' => 3263,
        'code2' => 'TW',
    ],
    [
        'code' => 'TZA',
        'name' => 'Tanzania',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 33517000,
        'local_name' => 'Tanzania',
        'capital' => 3306,
        'code2' => 'TZ',
    ],
    [
        'code' => 'UGA',
        'name' => 'Uganda',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 21778000,
        'local_name' => 'Uganda',
        'capital' => 3425,
        'code2' => 'UG',
    ],
    [
        'code' => 'UKR',
        'name' => 'Ukraine',
        'continent' => 'Europe',
        'region' => 'Eastern Europe',
        'population' => 50456000,
        'local_name' => 'Ukrajina',
        'capital' => 3426,
        'code2' => 'UA',
    ],
    [
        'code' => 'URY',
        'name' => 'Uruguay',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 3337000,
        'local_name' => 'Uruguay',
        'capital' => 3492,
        'code2' => 'UY',
    ],
    [
        'code' => 'USA',
        'name' => 'United States',
        'continent' => 'North America',
        'region' => 'North America',
        'population' => 278357000,
        'local_name' => 'United States',
        'capital' => 3813,
        'code2' => 'US',
    ],
    [
        'code' => 'UZB',
        'name' => 'Uzbekistan',
        'continent' => 'Asia',
        'region' => 'Southern and Central Asia',
        'population' => 24318000,
        'local_name' => 'Uzbekiston',
        'capital' => 3503,
        'code2' => 'UZ',
    ],
    [
        'code' => 'VAT',
        'name' => 'Holy See (Vatican City State)',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 1000,
        'local_name' => 'Santa Sede/Città del Vaticano',
        'capital' => 3538,
        'code2' => 'VA',
    ],
    [
        'code' => 'VCT',
        'name' => 'Saint Vincent and the Grenadines',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 114000,
        'local_name' => 'Saint Vincent and the Grenadines',
        'capital' => 3066,
        'code2' => 'VC',
    ],
    [
        'code' => 'VEN',
        'name' => 'Venezuela',
        'continent' => 'South America',
        'region' => 'South America',
        'population' => 24170000,
        'local_name' => 'Venezuela',
        'capital' => 3539,
        'code2' => 'VE',
    ],
    [
        'code' => 'VGB',
        'name' => 'Virgin Islands, British',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 21000,
        'local_name' => 'British Virgin Islands',
        'capital' => 537,
        'code2' => 'VG',
    ],
    [
        'code' => 'VIR',
        'name' => 'Virgin Islands, U.S.',
        'continent' => 'North America',
        'region' => 'Caribbean',
        'population' => 93000,
        'local_name' => 'Virgin Islands of the United States',
        'capital' => 4067,
        'code2' => 'VI',
    ],
    [
        'code' => 'VNM',
        'name' => 'Vietnam',
        'continent' => 'Asia',
        'region' => 'Southeast Asia',
        'population' => 79832000,
        'local_name' => 'Viêt Nam',
        'capital' => 3770,
        'code2' => 'VN',
    ],
    [
        'code' => 'VUT',
        'name' => 'Vanuatu',
        'continent' => 'Oceania',
        'region' => 'Melanesia',
        'population' => 190000,
        'local_name' => 'Vanuatu',
        'capital' => 3537,
        'code2' => 'VU',
    ],
    [
        'code' => 'WLF',
        'name' => 'Wallis and Futuna',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'population' => 15000,
        'local_name' => 'Wallis-et-Futuna',
        'capital' => 3536,
        'code2' => 'WF',
    ],
    [
        'code' => 'WSM',
        'name' => 'Samoa',
        'continent' => 'Oceania',
        'region' => 'Polynesia',
        'population' => 180000,
        'local_name' => 'Samoa',
        'capital' => 3169,
        'code2' => 'WS',
    ],
    [
        'code' => 'YEM',
        'name' => 'Yemen',
        'continent' => 'Asia',
        'region' => 'Middle East',
        'population' => 18112000,
        'local_name' => 'Al-Yaman',
        'capital' => 1780,
        'code2' => 'YE',
    ],
    [
        'code' => 'YUG',
        'name' => 'Yugoslavia',
        'continent' => 'Europe',
        'region' => 'Southern Europe',
        'population' => 10640000,
        'local_name' => 'Jugoslavija',
        'capital' => 1792,
        'code2' => 'YU',
    ],
    [
        'code' => 'ZAF',
        'name' => 'South Africa',
        'continent' => 'Africa',
        'region' => 'Southern Africa',
        'population' => 40377000,
        'local_name' => 'South Africa',
        'capital' => 716,
        'code2' => 'ZA',
    ],
    [
        'code' => 'ZMB',
        'name' => 'Zambia',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 9169000,
        'local_name' => 'Zambia',
        'capital' => 3162,
        'code2' => 'ZM',
    ],
    [
        'code' => 'ZWE',
        'name' => 'Zimbabwe',
        'continent' => 'Africa',
        'region' => 'Eastern Africa',
        'population' => 11669000,
        'local_name' => 'Zimbabwe',
        'capital' => 4068,
        'code2' => 'ZW',
    ],
];
